name: Molecule

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Ansible Role
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint molecule molecule-plugins[docker]

      - name: Run Ansible Lint
        run: ansible-lint .
  test:
    name: Test role with Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker ansible molecule molecule-plugins[docker]

      - name: Run Molecule test
        run: |
          molecule test
